name: My OpenAPIHub API CICD Update Job
 
on:
  push:
    branches:
      - main
 
jobs:
  openapihub-api-file-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: OpenAPIHub/github-api-sync@v1.0.0
        with:
          OAH_CLI_TOKEN: ${{secrets.OAH_CLI_TOKEN}}
          OAH_API_ID: ${{secrets.OAH_API_ID}}
          README_LOC: ''
          SWAGGER_LOC: ''
